#!/usr/bin/env python3
"""
Generate compressed product-mode frontend assets for ESP32-CAM firmware.

This script reads the SmallCar web frontend files from the repo's web/ directory
(index.html, setup.html, style.css, main.js, setup.js, config.js, favicon.svg,
placeholder-video.svg), gzips them, and emits a single header file
camera_index_product.h under esp32_cam/CameraWebServer/.

The header defines static const unsigned char arrays like
  product_index_html_gz[]
  product_main_js_gz[]
plus matching *_len size symbols.

Only the product firmware build (SMALLCAR_FW_PRODUCT) includes this header.

Run from the repo root:
  python3 esp32_cam/CameraWebServer/tools/embed_product_frontend.py
or from within esp32_cam/CameraWebServer:
  python3 tools/embed_product_frontend.py
"""

import gzip
from pathlib import Path
from typing import List, Tuple

# (symbol_base_name, source_relative_path)
ASSETS: List[Tuple[str, str]] = [
    ("product_index_html_gz", "index.html"),
    ("product_setup_html_gz", "setup.html"),
    ("product_style_css_gz", "style.css"),
    ("product_main_js_gz", "main.js"),
    ("product_setup_js_gz", "setup.js"),
    ("product_config_js_gz", "config.js"),
    ("product_favicon_svg_gz", "favicon.svg"),
    ("product_placeholder_video_svg_gz", "placeholder-video.svg"),
    ("product_version_txt_gz", "version.txt"),
]


def to_c_array(name: str, data: bytes) -> List[str]:
    """Format a byte sequence as a C static const unsigned char array."""
    hex_bytes = [f"0x{b:02X}" for b in data]
    lines: List[str] = [f"static const unsigned char {name}[] = {{"]

    per_line = 16
    for i in range(0, len(hex_bytes), per_line):
        chunk = ", ".join(hex_bytes[i : i + per_line])
        lines.append(f"  {chunk},")

    if len(lines) > 1 and lines[-1].endswith(","):
        lines[-1] = lines[-1][:-1]

    lines.append("};")
    return lines


def main() -> None:
    script_dir = Path(__file__).resolve().parent
    fw_dir = script_dir.parent  # esp32_cam/CameraWebServer
    repo_root = fw_dir.parent.parent  # smallcar repo root

    web_dir = repo_root / "web"
    if not web_dir.is_dir():
        raise SystemExit(f"web directory not found: {web_dir}")

    out_path = fw_dir / "camera_index_product.h"

    header_lines: List[str] = []
    header_lines.append("#pragma once")
    header_lines.append("#include <stddef.h>")
    header_lines.append("")
    header_lines.append("// Auto-generated by tools/embed_product_frontend.py; do not edit by hand.")
    header_lines.append("")

    for symbol, rel in ASSETS:
        src_path = web_dir / rel
        if not src_path.is_file():
            raise SystemExit(f"asset not found: {src_path}")

        raw = src_path.read_bytes()

        # For the embedded product firmware we always want the product profile
        # of the frontend, so we rewrite the activeProfile in config.js on the fly
        # before compressing it. This does not modify the original file on disk
        # and keeps router-hosted web builds unchanged.
        if rel == "config.js":
            try:
                text = raw.decode("utf-8")
                text = text.replace("activeProfile: \"geek\"", "activeProfile: \"product\"")
                raw = text.encode("utf-8")
            except UnicodeDecodeError:
                pass

        gz = gzip.compress(raw)

        header_lines.append(f"// {rel} -> {symbol} (gzip, {len(gz)} bytes)")
        header_lines.extend(to_c_array(symbol, gz))
        header_lines.append(f"static const size_t {symbol}_len = sizeof({symbol});")
        header_lines.append("")

    out_path.write_text("\n".join(header_lines), encoding="utf-8")
    print(f"Wrote {out_path} with {len(ASSETS)} assets.")


if __name__ == "__main__":
    main()
